# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         LWP-Authen-Negotiate
license:      perl
version:      0.04
abstract: LWP Authentication Plugin
author: Achim Grolms <perl@grolmsnet.de>
installdirs:  site
requires:
  GSSAPI: 0.18
  MIME::Base64: 2.12
distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
